var dialogs = [
    'Você veio... Para ser sincera não achei que viria',
    'No fim você ainda se culpa por não ter conseguido salvar eles',
    '...',
    'Bom, eles não vão voltar a vida, mas talvez você tenha uma chance de se vingar',
    'E junto, salvar tudo o que sobrou',
    'Nós conseguimos nos juntar e desenvolver uma arma que deve ser efetiva contra o Dominador',
    'Nós a apelidamos de BPQ, já que ela é um batedor de particulas quanticas',
    'Vou te poupar da explicação gigante de como funciona, mas ela deve vaporizar tudo que o Raio tocar',
    'Até mesmo o Dominador...',
    'Entretanto ela só da para usar uma vez',
    'Nós não temos pessoal nem material sobrando pra conseguir fazer outra',
    'Eu sei o quanto você perdeu Mark, e eu sei que dos que sobrou você é o que mais quer ver o Dominador morto',
    'Sinceramente eu não queria te colocar mais uma vez dentro de uma nave',
    'Mas você é nosso melhor piloto',
    'Aquele que nunca perdeu a esperança que esse planeta podia ser salvo',
    'O único que lutou até o fim mesmo tendo perdido tudo no caminho',
    'Nosso único... ',
    'Undertaker',
    '...',
    'Você subiria em uma nave pela última vez? Eu te prometo Mark, essa será a última batalha',
    'Eu...',
    'Eu já perdi muitas coisas Maria, já jurei inumeras vezes matar o Dominador com minhas proprias mãos',
    'A raiva passou a ser tristeza, e a tristeza eventualmente virou apatia',
    'Mas se eu tiver uma chance, uma única chance que seja, eu irei matar o Dominador',
    'Esse pensamento nunca saiu da minha cabeça, então mesmo que eu morra',
    'Eu aceito a missão',
    'Bom...',
    'Primeiramente não morra!',
    'Se ta rogando praga, ta parecendo cena de fim de filme que o protagonista vai enfrentar o vilão e morre na batalha',
    'Você trate de voltar vivo viu, eu to te mandando lá pra ganhar e não pra morrer!',
    '...',
    'Eu... Vou tentar, vou tentar voltar vivo, se eu morresse agora, quem sobraria pra lembrar dos que já caíram antes...',
    'Ah, assim é melhor, a arma já foi instalada na sua nave junto das suas armas padrão',
    'Você vai ter que lutar contra a gangue da aniquilação antes de chegar no Dominador',
    'Mas depois de tantos anos fazendo isso... Não acho que vai ter dificuldade',
    'Agora vai lá, e acaba com a raça dele',
    '...',
    'Obrigado...',
    'Pode ter certeza que eu vou matar ele'
]